name: Check Version

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to include in the triggered workflow (optional)'
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"

jobs:
  main:
    name: Check Version
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Trigger Workflow Dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN_TRIGGER }}" \
            https://api.github.com/repos/rzhy1/check-version/actions/workflows/check_version.yml/dispatches \
            -d '{"ref":"main", "inputs": {"message": "${{ github.event.inputs.message }}" }}'
    - name: Check Version
      run: |
        python check_version.py > README.md
    - name: Commit change
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add README.md
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 更新版本信息"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: main
