name: Check Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - released
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时运行一次
jobs:
  main:
    name: Check Version
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        #check-latest: true
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Check Version
      run: |
        output=$(python check_version.py)
        echo "Script output:"
        echo "$output"
        echo "$output" > README.md
        
        NOW=$(date '+%Y-%m-%d %H:%M:%S UTC')
        TIMESTAMP_LINE="-- 最新更新时间: ${NOW} --"
        README_CONTENT=$(cat README.md)
        NEW_README_CONTENT="${TIMESTAMP_LINE}\n${README_CONTENT}"
        echo -e "${NEW_README_CONTENT}" | tee README.md

        # 显示文件内容
        echo "Final README.md content:"
        cat README.md
        
    - name: Commit change
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main -f
          git add README.md -f
          git commit -m "Update version information"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: main
