name: Check Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"

jobs:
  main:
    name: Check Version
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'false'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Convert README.md to UTF-8
      run: |
        if ! file -i README.md | grep -q "charset=utf-8"; then
          iconv -f "$(file -i README.md | sed -n 's/.*charset=\(.*\);?/\1/p')" -t UTF-8//TRANSLIT//IGNORE README.md > README.md.new
          mv README.md.new README.md
        fi
    - name: Check Version
      run: |
        output=$(python check_version.py)
        echo "Script output:"
        echo "$output"
        echo "$output" > README.md
    - name: Debug
      run: |
        echo "README.md content:"
        od -c README.md
        echo "Script output:"
        output=$(python check_version.py)
        echo "$output"
        echo "Script output (od):"
        echo "$output" | od -c
    - name: Commit change
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main -f
          git add README.md -f
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 更新版本信息"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: main
